### PR TITLE
Setting default color to black. Should fix #18.

### LINKED ISSUE #18: Math.tex(r'\frac a b') will throws an error
Math.tex(r'\frac a b');
Math.tex(r'\frac a b', mathStyle: MathStyle.display);
Math.tex(r'\frac a b', mathStyle: MathStyle.text);

The above code all will throw a same error:
NoSuchMethodError: The getter 'color' was called on null.
Receiver: null
Tried calling: color

My development environment is win10+vscode.

### PR DESCRIPTION
**Pull request by Skyost**
The `Math` widget may try to use a color that doesn't exist in the resolved `TextStyle`. As everyone isn't overriding the default text color, it may result in a NPE.

See [this comment](https://github.com/znjameswu/flutter_math/issues/18#issuecomment-744008322) for more info.

### CODE REVIEW

File: lib/src/widgets/math.dart [hunk 1]
```diff
@@ -193,7 +193,7 @@ class Math extends StatelessWidget {
             ? FontOptions(fontWeight: effectiveTextStyle.fontWeight)
             : null,
         logicalPpi: logicalPpi,
-        color: textStyle.color,
+        color: textStyle.color ?? Colors.black,
```
Comment (znjameswu) [inline lib/src/widgets/math.dart:196]: Actually, we should instead change `textStyle` to `effectiveTextStyle` here.

**Review by znjameswu — CHANGES_REQUESTED** [review]

File: lib/src/widgets/math.dart (hunk 1 above)
Comment (znjameswu) [reply lib/src/widgets/math.dart]: I have changed it.
